sheet_db:
  adapter: "mysql2"
  encoding: "utf8"
  host: "127.0.0.1"
  database: "sheet_import"
  username: "root"
  password: "root"
  port: 3306
  socket: /tmp/mysql.sock

google_drive_api:
  client_id: "YOUR_COOGLE_CLIENT_ID.apps.googleusercontent.com"
  client_secret: "notasecret"
  email_address: "YOUR_GOOGLE_EMAIL_ADDRESS_OBFUSCATED@developer.gserviceaccount.com"
  certificate_fingerprints: "3f2e9294672ce1b8b7c6d68e8f575a261ae9bf60"
  auth_uri: "https://accounts.google.com/o/oauth2/auth"
  token_uri: "https://accounts.google.com/o/oauth2/token"
  redirect_uri: "urn:ietf:wg:oauth:2.0:oob"

dropbox_api:
  app_key: "CHANGE ME"
  app_secret: "CHANGE ME"
  self_account_token: "CHANGE ME"
  self2_account_token: "CHANGE ME"


